version: '3.3'
services:
  proxy:
    build: ./
    ports:
      - "8000:8000"
    links:
      - "server"
  server:
    build: ../../school-server/
    volumes:
      - "../../school-server:/go/src/app"
    ports:
      - "8080:8080"
    command:
      - "fresh"

