version: '3.3'
services:
  proxy:
    build: ./
    ports:
      - "8000:8000"
    links:
      - "server"
  server:
    build: ../../school-server/
    volumes:
      - "../../school-server:/go/src/app"
    ports:
      - "8080:8080"
    command:
      - "fresh"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: door
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
